function [fitresult, gof] = createFit(H, Tau)
%CREATEFIT(H,TAU)
%  Create a fit.
%
%  Data for 'createFit' fit:
%      X Input : H
%      Y Output: Tau
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jan-2020 09:39:59


%% Fit: 'createFit'.
[xData, yData] = prepareCurveData( H, Tau );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1.94174346855076 0.0655534413516196 0.00661529418817611];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



